### ISSUE TITLE
compiler depends on order of definition in file

### ISSUE THREAD

**Issue by emicklei** [gqlc/gqlc#11]
consider the following example

```
type Permissions {
    shoppingCart: Boolean!
}

extend type Query {
    permissions: Permissions!
}

type Query
```

The compiler sees an extension on Query and fails immediately because it is defined later in the file.  Such a file is created because we concatenate multiple files into one before using gqlc.

I think the compiler should use a two-phase method in resolving types and definitions ; first read all definitions then verify type completeness.

**Comment by emicklei** [comment]
this issue should have been reported in the /graphql repo instead.

**Comment by Zaba505** [comment]
Thanks for the report! I found this bug hiding in the gqlc/compiler package. I've begun work on refactoring/rewriting the gqlc/compiler package, which houses all the internal logic e.g. type validation, etc. I am expecting to have this work finished within the next day or so.

**Comment by Zaba505** [comment]
Issue #13 also falls under the gqlc/compiler package and will be fixed during the refactoring.
